# Generated by Django 3.1.1 on 2020-09-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0002_auto_20200916_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
